# Generated by Django 5.0.5 on 2024-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='image',
            field=models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to=''),
        ),
    ]
