# Generated by Django 5.0.5 on 2024-05-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
