# Generated by Django 5.0.5 on 2024-05-10 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_register_city_user_register_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pin_code', models.CharField(max_length=50, null=True)),
                ('c_year', models.CharField(max_length=50, null=True)),
                ('c_month', models.CharField(max_length=50, null=True)),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('fuel', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('no_owner', models.CharField(max_length=100, null=True)),
                ('kilometer', models.CharField(max_length=100, null=True)),
                ('selling_price', models.BigIntegerField(null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
