# Generated by Django 5.0.5 on 2024-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sell_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_form',
            name='image',
            field=models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to=''),
        ),
    ]
