# Generated by Django 5.0.5 on 2024-05-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sell_form_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='sell_form',
            name='image',
        ),
        migrations.AddField(
            model_name='sell_form',
            name='images',
            field=models.ManyToManyField(to='app.image'),
        ),
    ]
