# Generated by Django 5.0.5 on 2024-05-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image_remove_sell_form_image_sell_form_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_form',
            name='images',
        ),
        migrations.AddField(
            model_name='sell_form',
            name='image_1',
            field=models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sell_form',
            name='image_2',
            field=models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sell_form',
            name='image_3',
            field=models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sell_form',
            name='image_4',
            field=models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
