# Generated by Django 5.0.5 on 2024-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='postion',
            field=models.CharField(choices=[('employee', 'employee'), ('ex-employees', 'ex-employees')], default='employee', max_length=20),
        ),
    ]
