# Generated by Django 5.0.5 on 2024-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_register_postion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pin_code', models.CharField(max_length=50, null=True)),
                ('c_year', models.CharField(max_length=50, null=True)),
                ('c_month', models.CharField(max_length=50, null=True)),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('fuel', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('extra_features', models.CharField(max_length=100, null=True)),
                ('engine_type', models.CharField(max_length=100, null=True)),
                ('kilometer', models.CharField(max_length=100, null=True)),
                ('selling_price', models.CharField(max_length=100, null=True)),
                ('image_1', models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to='')),
                ('image_2', models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to='')),
                ('image_3', models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to='')),
                ('image_4', models.ImageField(help_text='<br><b>upload image!!<b>', null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='sell_form',
            name='features',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
