# Generated by Django 5.0.5 on 2024-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_selling_form_sell_form_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selling_form',
            old_name='selling_price',
            new_name='RC_transfer_Facilitation',
        ),
        migrations.AddField(
            model_name='selling_form',
            name='TCS',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selling_form',
            name='base_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selling_form',
            name='total_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selling_form',
            name='extra_features',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
