# Generated by Django 5.0.5 on 2024-05-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_selling_form_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling_form',
            name='employee_id',
        ),
    ]
