# Generated by Django 5.0.5 on 2024-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_selling_form_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_form',
            name='status',
            field=models.CharField(choices=[('On-Stack', 'On-Stack'), ('Out Of Stack', 'Out Of Stack')], default='On-Stack', max_length=100),
        ),
    ]
