# Generated by Django 5.0.5 on 2024-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_selling_form_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_form',
            name='features',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
