# Generated by Django 5.0.5 on 2024-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_sell_form_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_form',
            name='features',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
