# Generated by Django 5.0.5 on 2024-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_sell_form_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_form',
            name='downpay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selling_form',
            name='emi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selling_form',
            name='interest',
            field=models.CharField(default='8%', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selling_form',
            name='loan_d',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
