# Generated by Django 5.0.5 on 2024-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_selling_form_downpay_selling_form_emi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling_form',
            name='extra_features',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
