# Generated by Django 5.0.5 on 2024-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_selling_form_extra_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_form',
            name='emp_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
