# Generated by Django 5.0.5 on 2024-05-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_sell_form_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling_form',
            name='downpay',
        ),
        migrations.RemoveField(
            model_name='selling_form',
            name='emi',
        ),
        migrations.RemoveField(
            model_name='selling_form',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='selling_form',
            name='loan_d',
        ),
    ]
