# Generated by Django 5.0.5 on 2024-05-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_selling_form_downpay_remove_selling_form_emi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_form',
            name='approve',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Unapproved', 'Unapproved')], default='Unapproved', max_length=100),
        ),
    ]
