# Generated by Django 5.0.5 on 2024-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_form',
            name='status',
            field=models.CharField(choices=[(' ', ''), ('approved', 'approved'), ('rejected', 'rejected')], max_length=100),
        ),
    ]
