# Generated by Django 5.0.5 on 2024-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_sell_form_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_form',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected')], default='new', max_length=100),
        ),
    ]
